### ISSUE TITLE
Problems with herotabs and wordpress

### ISSUE THREAD

**Issue by sstudebaker** [simonsmith/jquery.herotabs#7]
I setup a test page and got this working exactly the way I want (http://5btech.net/test/) but when I move this into wordpress it will only set the tab-nav-current on the top tab and aria-selected is still set to false on all others when hovered on. Any ideas how to fix this?

**Comment by simonsmith** [comment]
I can only assume it sets some classes or ids of its own that interfere. Got an example of that too?

**Comment by sstudebaker** [comment]
Hey thanks for the reply!!

The page is here http://csoutdoorprogram.org/

username: ola
pass: 1973

I changed the home page to be the exact code used in the test (so not using wp header or footer function while I try to determine issue).

Only difference is that the menu is now being constructed by wordpress. It works perfectly until I swap the menu out. Using a child theme with twenty-thirteen.

I'm attaching page code:




On Feb 23, 2015, at 12:48 PM, Simon Smith <notifications@github.com> wrote:

> I can only assume it sets some classes or ids of its own that interfere. Got an example of that too?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Shirley Studebaker
5B Technologies
PO Box 3424
Ketchum, ID 83340
208.720.3963
www.5btech.net

**Comment by simonsmith** [comment]
I believe the bug lies with your sub menus. If you look at the wordpress version it is adding the `menu-item` class to those `<li>` elements too which seems to break things. Your static example does not have those classes present.

Can I also suggest that you don't override the default classes in the herotabs source, but instead pass them in as options to the plugin. Confused me for a bit as to how it was working :)

**Comment by sstudebaker** [comment]
Thanks I'll take a look.

Not sure how to pass in the styles to the menu though. I guess that would alleviate the issue with the sub-menu menu-item class.



On Feb 23, 2015, at 1:11 PM, Simon Smith <notifications@github.com> wrote:

> I believe the bug lies with your sub menus. If you look at the wordpress version it is adding the menu-item class to those <li> elements too which seems to break things. Your static example does not have those classes present.
> 
> Can I also suggest that you don't override the default classes in the herotabs source, but instead pass them in as options to the plugin. Confused me for a bit as to how it was working :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Shirley Studebaker
5B Technologies
PO Box 3424
Ketchum, ID 83340
208.720.3963
www.5btech.net

**Comment by sstudebaker** [comment]
I made the changes you suggested (shoudn't ask more questions until I look right?) and now the menu is working perfectly!!!

You're brilliant. Thank you.

**Comment by simonsmith** [comment]
Good to hear!
