### ISSUE TITLE
Destroy method?

### ISSUE THREAD

**Issue by brettgullan** [simonsmith/jquery.herotabs#8]
I'm looking to use herotabs in a responsive design, where the tab behaviour is only applied on smaller breakpoints -- i.e. mobile phones. I'm using Enquire.js to add/remove functionality as the breakpoints change.

Herotabs doesn't seem to have a destroy() method, that would let me remove/reinitialize it? Any thoughts on how I'd go about doing that?

Cheers,

Brett

**Comment by brettgullan** [comment]
I've put the following together, which seems to work OK. 
Not sure that it's the most elegant solution …

```
	Herotabs.prototype.destroy = function() {
	    
	    var options = this.options;
	    var eventType = this._getEventType();

	    this.nav
	    	.off('keydown', 'a')
	    	.off(eventType, 'a')
		.removeAttr('role');
	    
	    this.navItem
			.removeAttr('role');
			
		$('a', this.navItem)	
			.removeAttr('id')
			.removeAttr('role')
			.removeAttr('aria-selected')
			.removeAttr('tabindex');
	    
	    this.tab
			.show()
			.removeClass(options.css.active)
			.removeAttr('role')
			.removeAttr('aria-labelledby')
			.removeAttr('aria-hidden')
			.removeAttr('aria-selected')
			.removeAttr('tabindex')
			.removeAttr('style');

		this.container
	    		.off('mouseenter mouseleave')
			.removeClass(options.css.active)
			.css({
				'position': ''
			})
			.removeData('herotabs');
	};
```

**Comment by simonsmith** [comment]
I can take a look at adding this, sure.

However couldn't you just run `herotabs` between a min and max breakpoint? The only issue you'd have is if you resized your browser but users don't really do that :)
